### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by aaronkilik** [DanCRichards/ASCII-Art-Splash-Screen#2]
I get the following error.
![syntaxerror invalid syntax](https://user-images.githubusercontent.com/17021021/37446003-f4e8047c-282b-11e8-9e66-5fedd894f497.png)

How can i solve it?

**Comment by DanCRichards** [comment]
Hey, I am sorry you're experiencing this issue with ASCII-Art-Splash-Screen.

I have noticed that you have performed some editing on this program, the original program only contains 5 lines, and the error your are occurring is on line 7. 


Do you want to post your code so I can have a look through and see what is happening? 

I am more than happy to help. 


I do how ever think that there is a syntax error in your python code, as it looks as if the python interpreter is trying to run the code '<!DOCTYPE html>' which of course isn't python code at all. 
For you to print a HTML page onto a terminal screen you would have to use the CURL function (If it were to be on an external website) 


Cheers, 
Dan

**Comment by aaronkilik** [comment]
I was trying to use the wget command below to get the ascii.py file only:
<pre>wget https://github.com/DanCRichards/ASCII-Art-Splash-Screen/blob/master/ascii.py</pre>

Which saves it as an html file. 

So i had to clone the repository and installed the ascii.py file like this.
![download-and-into-ascii py-file](https://user-images.githubusercontent.com/17021021/37509554-d00095c4-2908-11e8-9684-e72d6937c43f.png)

And everything seems to be working fine. 

Thanks.

**Comment by DanCRichards** [comment]
Great to see t is all working for you! 

Thanks for that tutorial as well, looks great.

**Comment by aaronkilik** [comment]
You are most welcome.
